FROM alpine:latest

COPY usr/local/bin/docker-java-home /usr/local/bin/docker-java-home
COPY usr/lib/java/jdk-8u121 /usr/lib/java/jdk-8u121

ENV JAVA_VERSION 8u121
ENV JAVA_HOME /usr/lib/java/jdk-8u121
ENV PATH $PATH:/usr/lib/java/jdk-8u121/bin
