FROM debian:latest

COPY opt /opt

ENV GRADLE_VERSION=3.3 \
    ANT_VERSION=1.10.0 \
    MAVEN_VERSION=3.3.9

ENV PATH $PATH:/opt/gradle-$GRADLE_VERSION/bin:/opt/apache-ant-$ANT_VERSION/bin:/opt/apache-maven-$MAVEN_VERSION/bin
